-- MySQL Script generated by MySQL Workbench
-- Mon Aug 20 03:25:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema burgers_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `burgers_db` ;

-- -----------------------------------------------------
-- Schema burgers_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `burgers_db` DEFAULT CHARACTER SET utf8 ;
USE `burgers_db` ;

-- -----------------------------------------------------
-- Table `burgers_db`.`burgers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `burgers_db`.`burgers` ;

CREATE TABLE IF NOT EXISTS `burgers_db`.`burgers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `burger_name` VARCHAR(150) NOT NULL,
  `devoured` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
