INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Angus burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Bacon cheeseburger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Butter burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Buffalo burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('California burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Cheeseburger	');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Chili burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Hawaii burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Jucy Lucy');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Kimchi burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Luther Burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Naan burger	');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Patty melt');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Rice burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Salmon burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Slopper');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Slugburger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Steak burger	');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Steamed cheeseburger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Teriyaki burger');
INSERT INTO `burgers_db`.`burgers` (`burger_name`) VALUES ('Veggie burger');
